# Build
FROM node:lts-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ARG VITE_APP_MODE
ARG VITE_APP_HOST
ARG VITE_APP_PORT

ENV VITE_APP_MODE=$VITE_APP_MODE
ENV VITE_APP_HOST=$VITE_APP_HOST
ENV VITE_APP_PORT=$VITE_APP_PORT

RUN npm run build

# Serve
FROM nginx:alpine

ARG VITE_APP_HOST
ARG VITE_APP_PORT

ENV VITE_APP_HOST=$VITE_APP_HOST
ENV VITE_APP_PORT=$VITE_APP_PORT

# Copy built files from the builder stage
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy nginx templates
COPY nginx/nginx.conf.template /etc/nginx/templates/nginx.conf.template
COPY nginx/templates/10-server-name.conf.template /etc/nginx/templates/10-server-name.conf.template

EXPOSE 80

CMD ["/bin/sh", "-c", \
  "envsubst < /etc/nginx/templates/nginx.conf.template > /etc/nginx/nginx.conf && \
   envsubst < /etc/nginx/templates/10-server-name.conf.template > /etc/nginx/conf.d/10-server-name.conf && \
   exec nginx -g 'daemon off;'"]