# Build
FROM node:lts-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ARG VITE_APP_MODE
ARG VITE_APP_HOST
ARG VITE_APP_PORT

ENV VITE_APP_MODE=$VITE_APP_MODE
ENV VITE_APP_HOST=$VITE_APP_HOST
ENV VITE_APP_PORT=$VITE_APP_PORT

RUN npm run build

# Serve
FROM nginx:alpine

ARG VITE_APP_HOST
ENV VITE_APP_HOST=$VITE_APP_HOST

COPY --from=builder /app/dist /usr/share/nginx/html

COPY ./nginx/templates /etc/nginx/templates
COPY ./nginx/nginx.conf.template /etc/nginx/nginx.conf.template

RUN rm /etc/nginx/conf.d/default.conf && \
    envsubst < /etc/nginx/templates/10-server-name.conf.template > /etc/nginx/conf.d/default.conf && \
    envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]